### ISSUE TITLE
Error Ubuntu 18 Installation 

### ISSUE THREAD

**Issue by meldiwin** [zfergus/topopt#1]
Defaulting to user installation because normal site-packages is not writeable
Collecting topopt
  Using cached topopt-0.0.1a1.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fxyjh6bh/topopt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fxyjh6bh/topopt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-k3_w010s
         cwd: /tmp/pip-install-fxyjh6bh/topopt/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fxyjh6bh/topopt/setup.py", line 6, in <module>
        import topopt
      File "/tmp/pip-install-fxyjh6bh/topopt/topopt/__init__.py", line 6, in <module>
        from . import problems
      File "/tmp/pip-install-fxyjh6bh/topopt/topopt/problems.py", line 8, in <module>
        import cvxopt
    ModuleNotFoundError: No module named 'cvxopt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

**Comment by zfergus** [comment]
It looks like the CVXOPT python package is not installed. It is used to solve sparse linear systems. You can install it using `pip install cvxopt`.
